language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn docs:build
deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
